apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestion-cm
  labels: 
    {{- include "helmchart.labels" . | nindent 4 }}
data:
  nats.port: '{{ .Values.nats.nats.client.port }}'
  nats.address: '{{ .Release.Name }}-{{ .Values.nats.nameOverride }}.{{ .Release.Namespace }}.svc.cluster.local'