apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "helmchart.fullname" . }}-rb
subjects:
  - kind: ServiceAccount
    name: {{ template "helmchart.serviceAccountName" .}}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "helmchart.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io