{{- $apiToken := (randAlphaNum 45) | b64enc | quote }}
{{- $natsAuthToken := (randAlphaNum 45) | b64enc | quote }}
{{- if .Values.configuration.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: ingestion-secret
  labels: 
    "helm.sh/resource-policy": "keep"
    {{- include "helmchart.labels" . | nindent 4 }}
type: Opaque
data:
  ingestion.auth.token: {{ $apiToken }}
  nats.token: {{ $natsAuthToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ingestion-nats-config
  labels: 
    "helm.sh/resource-policy": "keep"
    {{- include "helmchart.labels" . | nindent 4 }}
type: Opaque
stringData:
  nats.conf: |
    port: 4222
    pid_file: "/var/run/nats/nats.pid"
    server_name:$POD_NAME
    jetstream {
      max_mem: 1Gi
      store_dir: /data
      max_file:10Gi
    }
    cluster {
      port: 6222
      name: nats
      routes = [
        nats://nats-cluster-0.nats-cluster.keas.svc.cluster.local:6222,nats://nats-cluster-1.nats-cluster.keas.svc.cluster.local:6222,nats://nats-cluster-2.nats-cluster.keas.svc.cluster.local:6222,

      ]
      cluster_advertise: $CLUSTER_ADVERTISE
      no_advertise: true

      connect_retries: 120
    }
    lame_duck_grace_period: 10s
    lame_duck_duration: 30s
    authorization: {
        token: {{ $natsAuthToken }}
    }
{{- end }}