{{- $apiToken := (randAlphaNum 45) | b64enc | quote }}
{{- if .Values.configuration.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: ingestion-secret
  labels: 
    "helm.sh/resource-policy": "keep"
    {{- include "helmchart.labels" . | nindent 4 }}
type: Opaque
data:
  ingestion.auth.token: {{ $apiToken }}
{{ end -}}