apiVersion: keas.io/v1alpha1
kind: IngestionPolicy
metadata:
  name: {{ include "helmchart.fullname" . }}
spec:
  description: Simple policy to only ingest
  defaults:
    allow: false
    ttl: -1
  policy: |
    allow { 
        input.payload.lastName == "world"
    }
    ttl = 60 {
        input.payload.firstName == "hello"
    }
---
apiVersion: keas.io/v1alpha1
kind: EventType
metadata:
  name: {{ include "helmchart.fullname" . }}
spec:
  description: "This is a type for testing"
  version: '0.0.1'
  type: TestType
  sources:
    - Gitlab
    - Github
  subTypes:
    - Created
    - Updated
    - Deleted
  schema: |
    {
      "$id": "https://example.com/person.schema.json",
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "title": "Person",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "firstName": {
          "type": "string",
          "description": "The person's first name."
        },
        "lastName": {
          "type": "string",
          "description": "The person's last name."
        },
        "age": {
          "description": "Age in years which must be equal to or greater than zero.",
          "type": "integer",
          "minimum": 0
        }
      }
    }
