{{ if .Values.eventTypes.spacelift.audit }}
apiVersion: keas.io/v1alpha1
kind: EventType
metadata:
  name: spacelift-audit-0-1-0
spec:
  schemaUri: https://schemas.keas.io/spacelift/audit/0.1.0
  description: Represents a flexibile audit entry in the Spacelift System
  schema: |
    {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://schemas.keas.io/spacelift/audit/0.1.0",
        "title": "Spacelift - AuditEntry - 0.1.0",
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "account": {
                "type": "string"
            },
            "action": {
                "type": "string"
            },
            "actor": {
                "type": "string"
            },
            "context": {
                "type": "object",
                "additionalProperties": true
            },
            "data": {
                "type": "object",
                "additionalProperties": true
            },
            "remoteIP": {
                "type": "string"
            },
            "timestamp": {
                "type": "number"
            }
        },
        "required": [
            "account",
            "action",
            "actor",
            "context",
            "data",
            "remoteIP",
            "timestamp"
        ]
    }
{{- end }}