apiVersion: v1
kind: Service
metadata:
  name: keas-{{ .Chart.Name }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{ if .Values.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helmchart.selectorLabels" . | nindent 4 }}
