{{- if .Values.configuration.createSecret }}
{{- $apiToken := (randAlphaNum 45) | b64enc | quote }}
apiVersion: v1
kind: Secret
metadata:
  name: connector-spacelift-secret
  labels: 
    helm.sh/resource-policy: "keep"
    {{- include "helmchart.labels" . | nindent 4 }}
type: Opaque
data:
  spacelift.webhook.token: {{ $apiToken }}
{{- end }}