apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "helmchart.serviceAccountName" .}}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
