apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "helmchart.serviceAccountName" .}}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs:     ["get", "watch", "list"]