apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "helmchart.serviceAccountName" .}}
subjects:
  - kind: ServiceAccount
    name: {{ template "helmchart.serviceAccountName" .}}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "helmchart.serviceAccountName" .}}
  apiGroup: rbac.authorization.k8s.io