apiVersion: v2
name: ingestion
description: Deploys the Ingestion API for Project Keas
type: application
kubeVersion: '>= 1.20.0'
keywords:
  - keas
  - ingestion
home: https://github.com/projectkeas/ingestion
sources:
  - https://github.com/projectkeas/ingestion
  - https://github.com/projectkeas/crds
  - https://github.com/projectkeas/helm/tree/main/charts/ingestion
deprecated: false
version: 0.2.2
appVersion: "0.2.2"
annotations:
  artifacthub.io/prerelease: 'true'
  artifacthub.io/license: MIT
dependencies:
  - name: "nats"
    version: "0.17.1"
    repository: "https://nats-io.github.io/k8s/helm/charts/"