image:
  repository: ghcr.io/projectkeas/ingestion
  pullPolicy: IfNotPresent
  tag: 
  pullSecrets: []

service:
  type: ClusterIP
  port: 80

serviceAccount:
  name:
  annotations: {}

configuration:
  createSecret: true

pod:
  annotations: {}
  securityContext: {}

resources: {}

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75

nodeSelector: {}

tolerations: []

affinity: {}

eventTypes:
  spacelift:
    audit: true

nats:
  nameOverride: 'ingestion-nats'
  nats:
    image: nats:2.9.0-alpine
    jetstream:
      enabled: true
      fileStorage:
        enabled: true
        size: 10Gi
        storageDirectory: /data/
  cluster:
    enabled: true
    noAdvertise: true
    extraRoutes: []
  natsbox:
    enabled: false
  exporter:
    enabled: false